name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
           login-server: vidyoportal.azurecr.io
           username: vidyoportal
           password: CkgJTc3fJuy5SbaEOxGw2wyC9FxnblIWhg1kkk5gDT+ACRA5JL6H
      - run: |
          docker build . -t vidyoportal.azurecr.io/sampleapp:latest
          docker push vidyoportal.azurecr.io/sampleapp:latest
